software_groups: &software
  - "base"
  - "apts3_build"

packages:
  branch_codenames:
    master: unstable
    production: stable

jobs:
  apt-s3:
    builder: "make"
    software_groups: *software
    base: "ubuntu:12.04"
    packages:
      - type: debian
        name: apt-transport-s3
        depends:
          - libcurl4-openssl-dev
          - libapt-pkg-dev
        repos:
          - mxm-public
        target: install
